kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      oidc-client-id: <YOUR_AZURE_AD_CLIENT_ID>
      oidc-issuer-url: https://sts.windows.net/<YOUR_AZURE_AD_TENANT_ID>/
      oidc-username-claim: oid
      oidc-groups-claim: groups
nodes:
- role: control-plane
  image: kindest/node:v1.29.1
- role: worker
  image: kindest/node:v1.29.1
