name: Azure Login
 
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install and configure kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Install and configure kubelogin
      run: |
        curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.9/kubelogin-linux-amd64.zip
        unzip kubelogin-linux-amd64.zip
        chmod +x ./bin/linux_amd64/kubelogin
        sudo mv ./bin/linux_amd64/kubelogin /usr/local/bin

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true

    # - name: Set Kubeconfig
    #   run: |
    #     kubelogin convert-kubeconfig -l spn --client-id ${{ secrets.AZURE_CLIENT_ID }} --client-secret ${{ secrets.AZURE_CLIENT_SECRET }}
    #     echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
    #     export KUBECONFIG=kubeconfig.yaml
    #     kubelogin convert-kubeconfig -l spn --client-id ${{ secrets.AZURE_CLIENT_ID }} --client-secret ${{ secrets.AZURE_CLIENT_SECRET }}
    #     kubectl config set-credentials azuread --token=${{ steps.azuread.outputs.token }}
    #     kubectl config set-context --current --user=azuread

    - name: Set Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Test kubectl commands
      run: |
        kubectl get nodes   